apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testadminbinding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: my-serviceaccount
  namespace: dev
  apiGroup: ""
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin

