[root@ip-172-31-83-19 ~]# cat springboot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31579

kubectl apply -f springboot-service.yaml

kubectl get svc or kubectl get services
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes           ClusterIP   10.96.0.1       <none>        443/TCP          83m
springboot-service   NodePort    10.111.220.26   <none>        8080:31579/TCP   17m

[root@ip-172-31-83-19 ~]# curl 10.111.220.26:8080
Greetings from Springboot..!!!
